# Generated by Django 3.1.1 on 2021-01-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0002_auto_20210121_1855'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commentsaaaaa',
            new_name='PanelComments',
        ),
    ]
