# Generated by Django 3.0.5 on 2021-02-26 03:34

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('panels', '0003_auto_20210121_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reporting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField(max_length=100000000)),
            ],
        ),
    ]
